server.port=80

spring.datasource.url=jdbc:sqlite:Database.db?journal_mode=WAL&date_string_format=yyyy-MM-dd HH:mm:ss&date_class=TEXT
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.username=
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect

spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.hibernate.ddl-auto=update

spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always

logging.config=classpath:log4j2.xml

jwt.secret=MySuperSecretKeyForProjectGameCoordinator2026!
# life time of token (one day)
jwt.refresh_expiration=86400000
jwt.access_expiration=30000